name: Update Radio EPG

on:
  schedule:
    - cron: '*/15 * * * *'   # runs every 15 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate epg.xml
        run: |
          echo "Creating epg.xml..."
          python3 << 'EOF'
import requests, html, datetime

url = "https://player.listenlive.co/63371/en/songhistory"
r = requests.get(url)
songs = r.json().get("songs", [])[:10]  # take 10 latest songs

now = datetime.datetime.utcnow()
xml = ['<?xml version="1.0" encoding="UTF-8"?>', '<tv generator-info-name="Radio EPG Script">']
xml.append('  <channel id="988"><display-name>988 FM</display-name></channel>')

for i, s in enumerate(songs):
    start = now - datetime.timedelta(minutes=i*15)
    stop = start + datetime.timedelta(minutes=15)
    title = html.escape(s.get("title", "Unknown Song"))
    artist = html.escape(s.get("artist", "Unknown Artist"))
    xml.append(f'''  <programme start="{start.strftime("%Y%m%d%H%M%S")} +0000" stop="{stop.strftime("%Y%m%d%H%M%S")} +0000" channel="988">
    <title lang="en">{title}</title>
    <desc>{artist}</desc>
  </programme>''')

xml.append("</tv>")

with open("epg.xml", "w", encoding="utf-8") as f:
    f.write("\n".join(xml))
EOF

      - name: Commit and push changes
        run: |
          git config --global user.emai
