name: Update Radio EPG

permissions:
  contents: write

on:
  schedule:
    - cron: '1 16 * * 0'  # Every Monday 0:01am
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Generate epg.xml
        run: python3 generate_epg.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add epg.xml
          git commit -m "Update EPG $(date -u)" || echo "No changes to commit"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Delete old workflow runs (keep latest 6)
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          OWNER: SGolden58
          REPO: radio
        run: |
          echo "Fetching all workflow runs..."
          runs=$(gh api --paginate "/repos/$OWNER/$REPO/actions/runs" --jq '.workflow_runs | sort_by(.created_at) | reverse | .[].id')
          count=0
          for run_id in $runs; do
            count=$((count+1))
            if [ $count -gt 6 ]; then
              echo "🗑️ Deleting workflow run ID: $run_id"
              gh api -X DELETE "/repos/$OWNER/$REPO/actions/runs/$run_id"
              sleep 1
            fi
          done
          echo "✅ Deleted all but latest 6 runs."
