# Configuration for updating EPG (Electronic Program Guide)
epg:
  url: "https://radio-online.my/988-fm-playlist"  # URL to fetch the playlist
  output_file: "epg.xml"  # Output filename for the generated XML
  max_songs: 60  # Maximum number of songs to include in the EPG
  programme_duration_minutes: 3  # Duration for each song in minutes
  timezone: "+0800"  # Timezone offset for the EPG
  generator_info_url: "https://sgolden58.github.io/radio/epg.xml"  # Generator info URL
