name: Update Radio EPG

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # runs every hour (optional)

permissions:
  contents: write    # ✅ allow writing files back to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Generate EPG XML
        run: python generate_epg.py

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add epg.xml
          git commit -m "Update EPG $(date)"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
