name: Update Radio EPG

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz

      - name: Generate epg.xml
        run: python3 generate_epg.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add epg.xml
          git commit -m "Update EPG $(date -u)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Delete old workflow runs (all workflows) keeping only 6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEEP_LATEST: 6
        run: |
          echo "Fetching all workflow runs..."
          ALL_RUNS=$(gh api repos/${{ github.repository }}/actions/runs \
            -q '.workflow_runs | sort_by(.created_at) | reverse | .['$KEEP_LATEST':] | .[].id')

          if [ -z "$ALL_RUNS" ]; then
            echo "Nothing to delete."
          else
            for RUN_ID in $ALL_RUNS; do
              echo "Deleting run $RUN_ID"
              gh api -X DELETE repos/${{ github.repository }}/actions/runs/$RUN_ID
            done
          fi
