name: Update EPG

# Run every 15 minutes
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies if any
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements file"

      # Step 4: Run your EPG Python script
      - name: Generate EPG
        run: |
          python epg_generator.py

      # Step 5: Commit and force push
      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add epg.xml
          git commit -m "Update EPG $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git fetch origin main
          git reset --hard origin/main
          git push origin main --force
