name: Update Radio EPG

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * 1' # every Monday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz

      - run: python3 generate_epg.py

      - run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add epg.xml
          git commit -m "Update EPG $(date -u)" || echo "No changes to commit"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Limit workflow runs to 6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEEP_LATEST: 6
        run: |
          echo "Fetching workflow runs..."
          runs=$(gh api repos/${{ github.repository }}/actions/workflows/$(gh api repos/${{ github.repository }}/actions/workflows | jq -r '.workflows[] | select(.name=="Update Radio EPG") | .id')/runs \
            -q '.workflow_runs | sort_by(.created_at) | reverse | .['$KEEP_LATEST':] | .[].id')
          
          if [ -z "$runs" ]; then
            echo "No runs to delete."
          else
            echo "Deleting old runs..."
            for run_id in $runs; do
              echo "Deleting run $run_id"
              gh api -X DELETE repos/${{ github.repository }}/actions/runs/$run_id
            done
          fi
